apiVersion: v1
kind: Namespace
metadata:
   name: dapi-test-app
   labels:
     name: dapi-test-app
---
apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  namespace: dapi-test-app
spec:
  containers:
  - name: test-container
    image: node:14.17.3-alpine
    command: [ "/bin/sh","-c","--" ]
    args: [ "while true; do sleep 30; done;" ]
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
    resources:
      requests:
        memory: "32Mi"
        cpu: "125m"
      limits:
        memory: "64Mi"
        cpu: "250m"  
  restartPolicy: Never